package com.gongyou.rongclouddemo.greendaobean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

/**
 * Entity mapped to table BLACK_LIST.
 */
@Entity
public class BlackList {
    /**定义主键*/
    @Id(autoincrement = true)
    private long id;
    /** Not-null value. */
    private String userId;
    private String status;
    private Long timestamp;
    @Generated(hash = 1200343381)
    public BlackList() {
    }
    @Generated(hash = 872070825)
    public BlackList(long id, String userId, String status, Long timestamp) {
        this.id = id;
        this.userId = userId;
        this.status = status;
        this.timestamp = timestamp;
    }
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        return "BlackList{" +
                "id=" + id +
                ", userId='" + userId + '\'' +
                ", status='" + status + '\'' +
                ", timestamp=" + timestamp +
                '}';
    }
}
