package com.gongyou.rongclouddemo.greendaobean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

/**
 * Entity mapped to table GROUPS.
 */
@Entity
public class Groups {
    /**定义主键*/
    @Id(autoincrement = true)
    private long id;
    private String userId;
    private String name;
    private String portraitUri;
    private String displayName;
    private String role;
    private String bulletin;
    private String timestamp;
    private String nameSpelling;


    @Generated(hash = 893039872)
    public Groups() {
    }
    @Generated(hash = 1294941195)
    public Groups(long id, String userId, String name, String portraitUri, String displayName, String role, String bulletin, String timestamp, String nameSpelling) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.role = role;
        this.bulletin = bulletin;
        this.timestamp = timestamp;
        this.nameSpelling = nameSpelling;
    }
    @Override
    public String toString() {
        return "Groups{" +
                "id=" + id +
                ", userId='" + userId + '\'' +
                ", name='" + name + '\'' +
                ", portraitUri='" + portraitUri + '\'' +
                ", displayName='" + displayName + '\'' +
                ", role='" + role + '\'' +
                ", bulletin='" + bulletin + '\'' +
                ", timestamp='" + timestamp + '\'' +
                ", nameSpelling='" + nameSpelling + '\'' +
                '}';
    }
    public void setId(long id) {

        this.id = id;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public void setBulletin(String bulletin) {
        this.bulletin = bulletin;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    public long getId() {

        return id;
    }

    public String getUserId() {
        return userId;
    }

    public String getName() {
        return name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getRole() {
        return role;
    }

    public String getBulletin() {
        return bulletin;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public String getNameSpelling() {
        return nameSpelling;
    }
}
