package com.gongyou.rongclouddemo.greendaobean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import android.net.Uri;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import io.rong.imlib.model.UserInfo;

/**
 * Entity mapped to table GROUP_MEMBER.
 */
@Entity
public class GroupMember{
    /**定义主键*/
    @Id(autoincrement = true)
    private long id;
    /** Not-null value. */
    private String groupId;
    private String userId;
    private String name;
    private String portraitUri;
    private String displayName;
    private String nameSpelling;
    private String displayNameSpelling;
    private String groupName;
    private String groupNameSpelling;
    private String groupPortraitUri;
    @Generated(hash = 1668463032)
    public GroupMember() {
    }
    @Generated(hash = 1090894699)
    public GroupMember(long id, String groupId, String userId, String name, String portraitUri, String displayName, String nameSpelling, String displayNameSpelling, String groupName, String groupNameSpelling, String groupPortraitUri) {
        this.id = id;
        this.groupId = groupId;
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.nameSpelling = nameSpelling;
        this.displayNameSpelling = displayNameSpelling;
        this.groupName = groupName;
        this.groupNameSpelling = groupNameSpelling;
        this.groupPortraitUri = groupPortraitUri;
    }
    public void setId(long id) {

        this.id = id;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    public void setDisplayNameSpelling(String displayNameSpelling) {
        this.displayNameSpelling = displayNameSpelling;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public void setGroupNameSpelling(String groupNameSpelling) {
        this.groupNameSpelling = groupNameSpelling;
    }

    public void setGroupPortraitUri(String groupPortraitUri) {
        this.groupPortraitUri = groupPortraitUri;
    }

    public long getId() {

        return id;
    }

    public String getGroupId() {
        return groupId;
    }

    public String getUserId() {
        return userId;
    }

    public String getName() {
        return name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getNameSpelling() {
        return nameSpelling;
    }

    public String getDisplayNameSpelling() {
        return displayNameSpelling;
    }

    public String getGroupName() {
        return groupName;
    }

    public String getGroupNameSpelling() {
        return groupNameSpelling;
    }

    public String getGroupPortraitUri() {
        return groupPortraitUri;
    }

    @Override
    public String toString() {
        return "GroupMember{" +
                "id=" + id +
                ", groupId='" + groupId + '\'' +
                ", userId='" + userId + '\'' +
                ", name='" + name + '\'' +
                ", portraitUri='" + portraitUri + '\'' +
                ", displayName='" + displayName + '\'' +
                ", nameSpelling='" + nameSpelling + '\'' +
                ", displayNameSpelling='" + displayNameSpelling + '\'' +
                ", groupName='" + groupName + '\'' +
                ", groupNameSpelling='" + groupNameSpelling + '\'' +
                ", groupPortraitUri='" + groupPortraitUri + '\'' +
                '}';
    }
}
