package com.gongyou.rongclouddemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gongyou.rongclouddemo.greendaobean.BlackList;
import com.gongyou.rongclouddemo.greendaobean.Friend;
import com.gongyou.rongclouddemo.greendaobean.GroupMember;
import com.gongyou.rongclouddemo.greendaobean.Groups;

import com.gongyou.rongclouddemo.greendao.BlackListDao;
import com.gongyou.rongclouddemo.greendao.FriendDao;
import com.gongyou.rongclouddemo.greendao.GroupMemberDao;
import com.gongyou.rongclouddemo.greendao.GroupsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig blackListDaoConfig;
    private final DaoConfig friendDaoConfig;
    private final DaoConfig groupMemberDaoConfig;
    private final DaoConfig groupsDaoConfig;

    private final BlackListDao blackListDao;
    private final FriendDao friendDao;
    private final GroupMemberDao groupMemberDao;
    private final GroupsDao groupsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        blackListDaoConfig = daoConfigMap.get(BlackListDao.class).clone();
        blackListDaoConfig.initIdentityScope(type);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        groupMemberDaoConfig = daoConfigMap.get(GroupMemberDao.class).clone();
        groupMemberDaoConfig.initIdentityScope(type);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        blackListDao = new BlackListDao(blackListDaoConfig, this);
        friendDao = new FriendDao(friendDaoConfig, this);
        groupMemberDao = new GroupMemberDao(groupMemberDaoConfig, this);
        groupsDao = new GroupsDao(groupsDaoConfig, this);

        registerDao(BlackList.class, blackListDao);
        registerDao(Friend.class, friendDao);
        registerDao(GroupMember.class, groupMemberDao);
        registerDao(Groups.class, groupsDao);
    }
    
    public void clear() {
        blackListDaoConfig.clearIdentityScope();
        friendDaoConfig.clearIdentityScope();
        groupMemberDaoConfig.clearIdentityScope();
        groupsDaoConfig.clearIdentityScope();
    }

    public BlackListDao getBlackListDao() {
        return blackListDao;
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public GroupMemberDao getGroupMemberDao() {
        return groupMemberDao;
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

}
